AxisCommunications/media-stream-library-js

- lib/components/aacdepay/aacdepay-component.js
- lib/components/auth/auth-component.js
- lib/components/basicdepay/basicdepay-component.js
- lib/components/h264depay/h264depay-component.js
- lib/components/helpers/stream-factory.js
- lib/components/inspector/inspector-component.js
- lib/components/mp4muxer/mp4muxer-component.js
- lib/components/mse/mse-component.js
- lib/components/replayer/replayer-component.js
- lib/components/rtsp-parser/rtspparser-component.js
- lib/components/tcp/tcp-component.js
- lib/components/websocket/websocket-component.js
- lib/components/xml-parser/xmlparser-component.js
To work around an issue with Edge, where the use
of shorthand method names together with using the
super keyword fails (Microsoft/ChakraCore/issues/5030)
Fixes #27
> Replace shorthand method names.

- lib/components/mp4muxer/mp4muxer-component.js
If there is no trackData yet, do not try to map
to either bitrate or framerate.
Fixes #39
> Do not access trackData if undefined.

- examples/node/player.js
- lib/pipelines/tcp-rtsp-mp4-pipeline.js
The Node CLI example now uses the correct API after
the changes introduced in 148c2ac.
> Fix the Node CLI example.

- lib/pipelines/index.browser.js
- lib/pipelines/metadata-pipeline.js
A pipeline to handle XML metadata, meant to
replace the old websocket-rtsp-xml pipeline.
> Metadata pipeline

- lib/components/auth/auth-component.js
- lib/pipelines/html5-video-pipeline.js
This PR adds support for authentication when streaming RTSP over websockets as I don't think it was possible for (at least for generic cameras). Essentially, it copies the pattern used by `CliMp4Pipeline` to  the class `Html5VideoPipeline` - allowing authentication params to be passed to in the config as in the following format:
```javascript
Pipeline = pipelines.Html5VideoPipeline
const pipeline = new Pipeline({
ws: { uri: `ws://localhost:8854` },
rtsp: { uri: `rtspurl` },
auth: { username: 'admin', password: 'mypassword' },
mediaElement
})
```
I tested out this change by updating the simple-player.js example to supply the username and password and streaming from a (non-Axis) camera.
As part of doing this change, I noticed that there was a hard-coded string in auth-component.js that …
> Add auth support for streaming RTSP over WS

- lib/components/rtsp-session/rtspsession-component.js
The RTP timestamp can wrap around, so that the difference
between the timestamps needs to account for the possibility
that one of them has wrapped.
> Guard against RTP timestamp wrap for NTP timestamp.

- lib/components/auth/digest.test.ts
- lib/components/auth/digest.ts
- lib/components/auth/fixtures.ts
- lib/components/auth/index.ts
- lib/components/auth/md5.d.ts
- lib/components/auth/www-authenticate.ts
- package.json
- yarn.lock
Because of the large overhead of using Node's crypto
library, replace www-authenticate with a custom auth
implementation for Basic and Digest auth, based on the
md5.js library.
> Replace www-authenticate with custom md5.js auth.

- lib/pipelines/tcp-ws-proxy-pipeline.ts
Sometimes you want to create websocket socket without server instance, and attach server later or handle WS upgrades somewhere in the application. 
For example: 
```
const proxy = new pipelines.TcpWsProxyPipeline( { noServer : true });
server.on('upgrade', (request, socket, head) => {
const path = url.parse(request.url).pathname;
if (path === '/ws-tcp-proxy') {
proxy.wss.handleUpgrade(request, socket, head, (ws) => {
proxy.wss.emit('connection', ws, request);
});
}
});
```
> WebSocket Server external use

- lib/components/onvifdepay/index.ts
The packets array was previously not initialized causing an error when trying
to push a value to undefined
Change-Id: If5eac9672477f896f0fb209cdbb02422d27cdd66
> fix: initialize ONVIF packets array

- lib/components/rtsp-parser/parser.test.ts
- lib/components/rtsp-parser/parser.ts
If the response was segmented in multiple chunks, the parser
would fail.
> Handle segmented RTSP messages

- examples/browser/camera/simple-metadata-player.js
- examples/browser/camera/simple-metadata.html
- lib/components/component.ts
- lib/components/onvifdepay/index.test.ts
- lib/components/onvifdepay/index.ts
- lib/pipelines/html5-video-metadata-pipeline.ts
- lib/pipelines/metadata-pipeline.ts
- Remove the `ONVIFDepay` handler. Instead this tube now only depays
the XML messages (as it did before). To handle the messages either
add a separate pipe to your pipeline after the Onvif one, or end
your pipeline with a sink where you can handle the messages.
- The `MetadataPipeline` now adds a handler sink at the end of the
pipeline that calls the metadata handler. This fixes a bug where
the pipeline would stall after `ONVIFDepay` would push messages
to a non-existing next pipe or sink.
- Add a new browser example on how to use the `MetadataPipeline`.
> fix(metadata)!: MetadataPipeline stops working after a while

- lib/components/tcp/index.ts
Remove timeout that closes the socket of TcpSource after a 2s inactivity. This will allow us to have the stream open even though no events are published from the device.
Closes #400
> Do not close TcpSource socket on inactivity

- package.json
The dependency `md5.js` is noted in `devDependencies`, but it is actually a production dependency since it is referenced from the class `DigestAuth`.
Closes #396
> Move md5.js to dependencies

- lib/components/tcp/index.ts
We're subscribing to the `socket.finish` event, but no such event exists according to the [official NodeJS documentation](https://nodejs.org/api/net.html#net_class_net_socket). There is one called `socket.end` though, lets use that one.
We can close #227 after merging this PR.
Closes #403
> Let TcpSource subscribe to the correct event

- lib/components/rtsp-parser/index.ts
We're using media-stream-library in our node project and we unfortunately experience hard process.exits if the rtsp client tries to setup a connection to a device/server that's not able to serve rtsp, but instead responds with 404 for example.
This fix prevents this crash and instead propagates the error up the pipeline.
> Prevent process exit on parse error

- package.json
Trying to have default entry points for both
node and browser seems to be a bit of a mess
to have it work properly for all kinds of
environments.
Instead, only browser entry points are exposed,
with the `browser` field pointing to the bundle
(so you don't need to be able to bundle the
browserify parts yourself when using this).
If using with Node.js, you'll have to import
from `dist/cjs/index.node.js` directly.
> feat!: expose browser by default

- webpack.config.js
Since the bundle is the main entry point now,
it should allow for use with e.g. Webpack.
> fix: export bundle as UMD libraryTarget

- lib/components/http-source/index.ts
- lib/pipelines/http-mse-pipeline.ts
Allow to terminate HTTP source by aborting
the fetch, and closing the response stream.
> fix: add `close` method to HTTP source

- lib/components/mse/index.ts
It can happen that appendBuffer fails because the
video element was already removed. To avoid unnecessary
error logs in those cases, replace those with a debug
log instead. The error was not reported on the stream
anyway, so it's only really useful for debugging
purposes.
> chore: use debug print to report appendBuffer problems

- lib/components/rtsp-session/index.test.ts
- lib/components/rtsp-session/index.ts
- lib/utils/protocols/rtsp.ts
Improve how the control URL is constructed, follow RFC. See #306 for more information.
> Use properly constructed URI in RTSP PLAY command

- .github/workflows/verify.yml
- lib/components/mp4capture/index.test.ts
- lib/components/mp4capture/index.ts
The start of a new movie is indicated by the tracks
property present on the ISOM box, as the SDP is no
longer transmitted after the MP4 muxer.
> fix: use ISOM tracks instead of SDP as start of movie

- lib/components/http-mp4/index.ts
- lib/components/message.ts
- lib/components/mse/index.ts
- lib/pipelines/http-mse-pipeline.ts
We need to set the content type from the response headers of streaming
MP4 on the media source.  This is implemented as a separate component
(as it only works for MP4 data over HTTP), while the original HTTP
source component remains unchanged (for any kind of data).
The HttpMsePipeline now uses the new HttpMp4 source and therefore skips
the MP4 parser component completely. There should be no noticeable
change when using that pipeline, other than not being able to get access
to separate boxes.
Additionally, expose all headers on both HTTP sources to users (via
component and pipeline onHeaders callback).
BREAKING CHANGE: no longer possible to access ISOM boxes on the
HttpMsePipeline (if you used this, then you need to construct the
old pipeline yourself).
> feat: use HTTP headers from streaming MP4

- lib/components/http-mp4/index.ts
- lib/components/http-source/index.ts
- lib/pipelines/http-mse-pipeline.ts
This also closes the stream when an error happens on the http sources.
> feat: add onServerClose callback to http sources

- .yarn/versions/9f7df4a4.yml
- lib/pipelines/html5-canvas-pipeline.ts
- lib/pipelines/html5-video-pipeline.ts
Sends a TEARDOWN message to invalidate
the rtsp session.
Our client never sends the TEARDOWN message when stopping
- Fixes #687
> fix: stop rtsp session when closing pipeline

- .github/workflows/stale.yml
If an issue is not a bug, mark it as stale after 90 days and close it after another 90 days.
If an issue was labeled as a bug, it's exempt from this and always has to be closed manually.
> chore: automatically mark issues as stale

- .github/workflows/publish.yml
> chore: install just in publish workflow

- overlay/package.json
- player/package.json
- scripts/changelog.mjs
- streams/package.json
When using TypeScript the exports field is not
working unless using moduleResolution node16,
which we don't want to enforce.
Instead, fallbacks are added back so that these
projects can still use moduleResolution node.
> chore: add fallback package exports

- player/README.md
- player/esbuild.mjs
- player/package.json
- streams/README.md
- streams/esbuild.mjs
- streams/package.json
Some dependencies are difficult to handle by external bundlers, especially the node deps replaced for the browser.
In that case, we can allow to e.g.:
```
import { ... } from 'media-stream-player/heavy'
```
which already includes those dependencies.
Not everything is bundled though.
Fixes #743
> feat: export modules that include dependencies

- overlay/esbuild.mjs
- package-lock.json
- player/README.md
- player/esbuild.mjs
- player/package.json
- streams/README.md
- streams/esbuild.mjs
- streams/package.json
- streams/polyfill.mjs
Ever since the change away from automatically bundling browser-equivalents of `Buffer` and `stream` Node.js dependencies, there have been a number of issues with bundling. Since this is such a problem, the proposal is to fix it by including the bundle as default, prioritizing ease-of-use over bundle size.
The bundle size in most cases won't be affected however, so this change should go mostly unnoticed except for people using their own bundler (vite, CRA, webpack, etc) having less headaches.
For those very special use-cases where it's adamant to bundle manually, there is a "light" version of `media-stream-library` where you need to deal with the bundling yourself.
Fixes #754
> fix!: bundle stream-browserify/process by default

- player/src/PlaybackArea.tsx
- player/src/Stats.tsx
- player/src/StillImage.tsx
- player/src/constants.ts
- player/src/types.ts
- player/src/utils/browserSupportedFormats.ts
A more basic endpoint for mjpeg exists in /mjpg/video.mjpg. This is basically a multipart stream of never ending jpeg images, which are delivered using "best effort".
- Fixes #811
> feat(player): add support for /mjpg/video.mjpg

- .eslint-rules.cjs
- justfile
- package-lock.json
- package.json
Update `@typescript-eslint` dependencies from version 5 to 6.
Since this required updating two deps simultaneously, the justfile
`update` command was changed to allow for more than 1 package.
> chore(dev-deps): update @typescript-eslint

- scripts/ci-video-test.sh
This updates cypress docker image used for tests.
> chore(dev-deps): bump cypress from 12.8.1 to 13.5.0

- overlay/esbuild.mjs
- overlay/package.json
- player/esbuild.mjs
- player/package.json
- streams/esbuild.mjs
- streams/package.json
The Babel interpretation should be used when modules are imported for the browser, which is not the case if the extension is .mjs (in which case Node interpretation is used). See https://esbuild.github.io/content-types/#default-interop
> fix: replace .mjs with .js extension for browser modules

- streams/src/components/mp4muxer/helpers/boxbuilder.ts
Non monotonic streams can produce negative sample duration and result in RangeError: "value" argument is out of bounds.
This isn't correct behaviour, but by setting the duration to zero a crash is prevented.
Fixes #294
Fixes #652
> fix: force negative frame durations to zero

- CHANGELOG.md
- package.json
- src/player/HttpMp4Video.tsx
- src/streams/http-mp4-pipeline.ts
Expose details about response headers and stream end so that the player can use that data.
> fix: export more data from the HTTP+MP4 pipeline

- CHANGELOG.md
- package.json
- src/streams/components/rtsp/session.ts
When a rtsp stream has ended, the keepalive continued to trigger. This caused an error in the console since the message could not be enqueued.
> fix(streams): handle rtcp bye with keepalive

- src/streams/components/rtp/h264-depay.ts
Updates H.264 parser to handle NAL type 6 "SEI", carrying supplemental enhancement information, used e.g. for Axis [signed video framework](https://github.com/AxisCommunications/signed-video-framework/blob/master/README.md).
> feat(streams): add support for SEI NAL units

- src/streams/components/mse-sink.ts
The severity when a stream is aborted was error, which is too high.
> fix(streams): log abort as info
