AxisCommunications/media-stream-library-js

README.md, examples/browser/README.md, examples/browser/flodhast.min.js, examples/browser/index.html, examples/browser/media-stream-library.min.js, examples/browser/player.js, webpack.config.js
Updated the library name in the examples and build.
=> Correct name of library in examples and build

CONTRIBUTING.md, README.md, examples/node/README.md
Added a first version of contribution guidelines, which will be referenced by all subsequent pull requests, like so: https://help.github.com/articles/setting-guidelines-for-repository-contributors/
Also fixed some minor typos in readmes.
Should we perhaps also create templates for issues and pull requests?
Would be nice to tick off this checklist:
https://github.com/AxisCommunications/media-stream-library-js/community
=> First version of contribution guidelines

examples/node/README.md
Updated the readme for the Node example.
=> Node example readme updated

lib/components/h264depay/h264depay.js, lib/components/mp4capture/mp4capture-component.js, lib/components/mp4muxer/mp4muxer-component.js, lib/components/rtsp-session/rtspsession-component.js, lib/components/websocket/websocket-component.js
Use the abbreviation 'msl' for 'Media Stream Library' in debug
messages.
=> Replace debug message live -> msl

examples/browser-sync/README.md, examples/browser-sync/index.html, examples/browser-sync/media-stream-library.min.js, examples/browser-sync/player.js, examples/rtsp-ws-browser-sync/README.md, examples/rtsp-ws-browser-sync/index.html, examples/rtsp-ws-browser-sync/media-stream-library.min.js, examples/rtsp-ws-browser-sync/player.js, examples/rtsp-ws-browser-sync/run.sh, lib/components/component.js, lib/components/helpers/stream-factory.js, lib/components/index.browser.js, lib/components/mp4muxer/mp4muxer-component.js, lib/components/mse/mse-component.js, lib/index.browser.js, lib/index.node.js, lib/pipelines/rtsp-mp4-pipeline.js, lib/utils/index.browser.js, lib/utils/index.node.js, lib/utils/scheduler.js
Support for synchronization is improved by letting the user know when
the start of presentation time is available through an `onSync` handler
on the MP4 component.
The usage of handlers on the MSE component is removed (breaking change!)
as the original idea was that synchronization would be handled there, but it's
really the wrong place. Instead, with the presentation time knowledge from MP4
component, you can synchronize anything directly with the video element.
To help with this, a new `Scheduler` class was added that can do this for you.
You send in the video element and a callback that you would like to schedule.
=> [breaking] Improve support for synchronization

lib/components/canvas/canvas-component.js, lib/components/helpers/stream-factory.js, lib/pipelines/html5-canvas-pipeline.js
- when clock is started and size is available,
call .onPlaying handler if it exists.
- fix bug in HtmlCanvasPipeline
=> Add onPlaying handler to Canvas component.

examples/browser/camera/simple-overlay-player.js, examples/browser/camera/simple-player.js, examples/browser/test/h264-overlay-player.js, examples/browser/test/h264-player.js, examples/browser/test/mjpeg-player.js
- solves some bugs with examples
- properly switch between H.264/MJPEG
- remove console.log
=> Improve examples.

examples/browser/camera/simple-overlay-player.js, examples/browser/camera/simple-player.js, examples/browser/test/h264-player.js, examples/browser/test/mjpeg-overlay-player.js, examples/browser/test/mjpeg-overlay.html, examples/browser/test/mjpeg-player.js, lib/components/canvas/canvas-component.js, lib/components/mse/mse-component.js, lib/pipelines/html5-canvas-pipeline.js, lib/pipelines/html5-video-pipeline.js, lib/pipelines/rtsp-mp4-pipeline.js, lib/pipelines/rtsp-pipeline.js, lib/utils/scheduler.js
The pipeline concept is further improved to allow
easier use for scheduling and control, withouth needing
to access separate components inside the pipeline.
The idea is that a pipeline should (eventually) be the
only thing needed to control playback and synchronization,
making it easier to build a proper basic player.
- The scheduler can be suspended and resumed,
to prevent control of the clock while some
other controller would like to pause.
Needed to be able to pause MJPEG playback.
- Properties that are needed by the scheduler to
control a clock are exposed on the H.264 and
motion JPEG RTSP pipelines, so that the pipelines
can be used as a clock by the scheduler.
- The methods on the RTSP session component that
control play, pause, and stop are now accessible
through the `rtsp` …
=> [breaking] Improved pipelines.

webpack.config.js
The production mode should automatically take care
of minification.
=> Remove uglifyjs-webpack-plugin

lib/components/rtsp-session/rtspsession-component.js, lib/components/rtsp-session/rtspsession-component.test.js, lib/utils/protocols/fixtures.js, lib/utils/protocols/rtsp.js, lib/utils/protocols/rtsp.test.js
This is derived from former pull request #101 
I've copied the former changes and adapted according to the comments
=> Feature: renew RTSP session

tsconfig.json
=> On build make sure typescript declaration files are included

.travis.yml, lib/components/auth/digest.ts, lib/components/h264depay/index.ts, lib/components/jpegdepay/index.ts, lib/components/rtsp-session/index.ts, package.json
Create scripts to check prettier formatting, add prettier checks to linting, and add linting to automated tests.
=> Add linting as part of CI

lib/components/index.node.ts
Make the Component type available for node
=> export Component for node

lib/components/h264depay/index.ts, lib/components/h264depay/parser.test.ts, lib/components/h264depay/parser.ts
Instead of keeping the buffer outside of the parser,
use a class instead which keeps track of the buffer
internally.
The `.parse` method on the class either returns a
new H.264 message, or null (in case there is no message
yet). In all cases, it keeps an internal buffer with
data that's part of the next message.
This leverages the parser's logic to determine if
the message is an I-frame in order to determine the
start of the stream (instead of coding it explicitly
in the transform stream).
=> chore: refactor H.264 depay as a class

package.json
=> Move yargs to dev dependencies

lib/utils/protocols/sdp.ts
Support for additional extension attribute.
=> feat: add x-sensor-transform attribute

.editorconfig, .github/workflows/verify.yml, examples/browser/test/h264-player.js, lib/components/tcp/index.ts, lib/pipelines/tcp-ws-proxy-pipeline.ts, sbin/tcp-ws-proxy.js, sbin/test.sh
Test on multiple browsers (chromium, firefox, edge),
and at the same time only use a stable NodeJS version.
=> chore(ci): test on multiple browsers

lib/components/h264depay/index.ts
Combine NAL units for same frame into a single `mdat`
box, by checking the RTP marker bit which signals the
end of a full frame.
=> fix: collect H.264 NAL units belonging to same frame

lib/components/mse/index.ts
When an error occurred, we should not try to access
any object (MediaSource instance or SourceBuffer) that
might not have been instantiated.
Furthermore, the error message should be propagated to
the log.
=> fix: prevent accessing source buffer after error

player/README.md, player/src/HttpMp4Video.tsx, player/src/WsRtspCanvas.tsx, player/src/WsRtspVideo.tsx, player/src/hooks/useVideoDebug.ts
Show debug logs for delay, current time and buffered end. In our application we are experiencing
a big delay and these logs will be of help to debug this issue. 
- Fixes #702
=> feat(player): add debug logs

.github/workflows/verify.yml
=> chore: support merge queues

.github/workflows/publish.yml, .github/workflows/verify.yml, streams/package.json, yarn.lock
=> chore(deps): upgrade to Node.js v20

.github/workflows/verify.yml, streams/esbuild.mjs
=> test: add build verification for Node.js v22

README.md, example-streams-web/README.md
=> docs: add quick install steps for example

.github/workflows/publish.yml, .github/workflows/verify.yml, example-overlay-react/package.json, example-player-react/package.json, overlay/package.json, package.json, player/package.json, streams/package.json, yarn.lock
=> chore: upgrade dependencies (major)

CHANGELOG.md, overlay/package.json, package.json, player/package.json, streams/package.json, yarn.lock
=> release: 13.3.1

.github/workflows/publish.yml, CHANGELOG.md, package.json
=> fix: use "next" take for alpha/beta versions

.github/workflows/publish.yml, CHANGELOG.md, package.json
=> fix: use bundle assets from project root

CHANGELOG.md, CONTRIBUTING.md, package.json
=> docs: update CONTRIBUTING.md with new release flow

.github/workflows/verify.yml, CHANGELOG.md, package.json
=> fix: add license field to package.json

.yarnrc.yml
=> fix: update package.json version on release

src/streams/components/rtsp/session.ts
Adds a URI option to the describe method in the RTSP session. If provided, it's used for that session instead of the URI that was provided to the constructor. The latter now only serves as default URI when none is provided to describe.
On teardown, the session control URL is restored to the default.
Fixes #1077
=> feat(streams): allow changing the RTSP URI

.github/workflows/publish.yml
=> chore: upload release assets

.github/dependabot.yml, example-overlay-react/package.json, example-player-react/package.json, package.json, src/overlay/hooks/useDraggable.ts, src/player/BasicPlayer.tsx, src/player/HttpMp4Video.tsx, src/player/Settings.tsx, src/player/WsRtspCanvas.tsx, src/player/WsRtspVideo.tsx, src/player/components/Limiter.tsx, src/player/hooks/useEventState.ts, src/player/hooks/useInterval.ts, src/player/hooks/useUserActive.ts, yarn.lock
Changes dependabot config to group any react-related updates, so e.g. react and react-dom are updated together.
=> fix: update react and keep related updates together

example-player-react/App.jsx
=> fix(example-player-react): don't use boolean className

example-overlay-react/package.json, example-overlay-react/vite.mjs, example-player-react/package.json, example-player-react/vite.mjs, package.json, yarn.lock
The react plugin isn't strictly necessary and comes with a whole bunch of extra dependencies, so it's better to remove it.
=> chore: remove vite's react plugin

.github/workflows/codeql.yml, .github/workflows/docker.yml, .github/workflows/publish.yml, .github/workflows/stale.yml, .github/workflows/verify.yml
=> chore: pin workflow dependencies (actions, docker images)

.github/workflows/verify.yml, gst-rtsp-launch/Dockerfile, scripts/rtsp-server.sh
=> chore: pin docker base image

.github/workflows/codeql.yml, .github/workflows/docker.yml, .github/workflows/publish.yml, .github/workflows/stale.yml, .github/workflows/verify.yml
=> chore: set explicit workflow permissions

src/streams/openwebsocket.ts
The workaround for handling websocker in safari, when using an apple device, has not worked for some time. This new workaround is not as elegant since it assumes that this always is an issue for safari.
=> fix(stream): extra login for safari
